name: Notify Discord on PR

on:
  pull_request:
    types: [opened]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"📣 New PR by ${{ github.actor }}: ${{ github.event.pull_request.title }}\n🔗 ${{ github.event.pull_request.html_url }}\"}" \
               "${{ secrets.DISCORD_WEBHOOK_PR }}"
